aliases: []
creation_timestamp: 1731009860896
current_stage: None
description: null
last_updated_timestamp: 1731009860896
name: LogisticRegression_Heart_Model
run_id: e2ffbcd27d484c07ad0b13a045a360ae
run_link: null
source: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/e2ffbcd27d484c07ad0b13a045a360ae/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/e2ffbcd27d484c07ad0b13a045a360ae/artifacts/model
user_id: null
version: 5
