aliases: []
creation_timestamp: 1731316789045
current_stage: None
description: null
last_updated_timestamp: 1731316789045
name: LogisticRegression_Heart_Model
run_id: 76347715d8cb4fcaa40b688d58f03b1e
run_link: null
source: file:///D:/Supinfo/M2/Ml/MLD/projet/mlflow_run/231975655115258684/76347715d8cb4fcaa40b688d58f03b1e/artifacts/model
status: READY
status_message: null
storage_location: file:///D:/Supinfo/M2/Ml/MLD/projet/mlflow_run/231975655115258684/76347715d8cb4fcaa40b688d58f03b1e/artifacts/model
user_id: null
version: 1
