aliases: []
creation_timestamp: 1730995491332
current_stage: None
description: null
last_updated_timestamp: 1730995491332
name: RandomForest_Heart_Model
run_id: 07b797b83dbd4ef5b777a43a77a07cc4
run_link: null
source: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/07b797b83dbd4ef5b777a43a77a07cc4/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/07b797b83dbd4ef5b777a43a77a07cc4/artifacts/model
user_id: null
version: 2
