artifact_location: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650
creation_time: 1730993990811
experiment_id: '664836091588214650'
last_update_time: 1730993990811
lifecycle_stage: active
name: experience_1
