artifact_location: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/projet_mlops/scripts/mlflow_run/0
creation_time: 1730995324142
experiment_id: '0'
last_update_time: 1730995324142
lifecycle_stage: active
name: Default
