aliases: []
creation_timestamp: 1730997559811
current_stage: None
description: null
last_updated_timestamp: 1730997559811
name: RandomForest_Heart_Model
run_id: bb7ce6748fb54861b6e9f7e59af0fff6
run_link: null
source: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/bb7ce6748fb54861b6e9f7e59af0fff6/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/bb7ce6748fb54861b6e9f7e59af0fff6/artifacts/model
user_id: null
version: 5
