artifact_uri: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/07b797b83dbd4ef5b777a43a77a07cc4/artifacts
end_time: 1730995491390
entry_point_name: ''
experiment_id: '664836091588214650'
lifecycle_stage: active
run_id: 07b797b83dbd4ef5b777a43a77a07cc4
run_name: thoughtful-jay-972
run_uuid: 07b797b83dbd4ef5b777a43a77a07cc4
source_name: ''
source_type: 4
source_version: ''
start_time: 1730995480876
status: 3
tags: []
user_id: HP
