artifact_uri: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/e21bb73ab3ee4ebd9ae266d0b2275f78/artifacts
end_time: 1731008167954
entry_point_name: ''
experiment_id: '664836091588214650'
lifecycle_stage: active
run_id: e21bb73ab3ee4ebd9ae266d0b2275f78
run_name: youthful-crane-443
run_uuid: e21bb73ab3ee4ebd9ae266d0b2275f78
source_name: ''
source_type: 4
source_version: ''
start_time: 1731008164423
status: 3
tags: []
user_id: kanfa
