artifact_uri: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/64b90aeccfde4ec89fa0f351812326fc/artifacts
end_time: 1731007646308
entry_point_name: ''
experiment_id: '664836091588214650'
lifecycle_stage: active
run_id: 64b90aeccfde4ec89fa0f351812326fc
run_name: legendary-cod-60
run_uuid: 64b90aeccfde4ec89fa0f351812326fc
source_name: ''
source_type: 4
source_version: ''
start_time: 1731007642902
status: 4
tags: []
user_id: kanfa
