aliases: []
creation_timestamp: 1730995875892
current_stage: None
description: null
last_updated_timestamp: 1730995875892
name: LogisticRegression_Heart_Model
run_id: 621430a45d1c4fee83d80a909b0b19b5
run_link: null
source: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/621430a45d1c4fee83d80a909b0b19b5/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/621430a45d1c4fee83d80a909b0b19b5/artifacts/model
user_id: null
version: 2
