artifact_uri: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/e01bdebeeace40e09649b7b9096f1908/artifacts
end_time: 1730994402524
entry_point_name: ''
experiment_id: '664836091588214650'
lifecycle_stage: active
run_id: e01bdebeeace40e09649b7b9096f1908
run_name: welcoming-mouse-842
run_uuid: e01bdebeeace40e09649b7b9096f1908
source_name: ''
source_type: 4
source_version: ''
start_time: 1730994392828
status: 3
tags: []
user_id: HP
