channels:
- conda-forge
dependencies:
- python=3.11.1
- pip<=24.3.1
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.1.0
  - numpy==1.26.4
  - pandas==1.5.3
  - psutil==6.1.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
