artifact_uri: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/e2ffbcd27d484c07ad0b13a045a360ae/artifacts
end_time: 1731009860911
entry_point_name: ''
experiment_id: '664836091588214650'
lifecycle_stage: active
run_id: e2ffbcd27d484c07ad0b13a045a360ae
run_name: auspicious-seal-703
run_uuid: e2ffbcd27d484c07ad0b13a045a360ae
source_name: ''
source_type: 4
source_version: ''
start_time: 1731009857034
status: 3
tags: []
user_id: kanfa
