aliases: []
creation_timestamp: 1731316775847
current_stage: None
description: null
last_updated_timestamp: 1731316775847
name: RandomForest_Heart_Model
run_id: d6a0ed34f7344752ac260759357ab98b
run_link: null
source: file:///D:/Supinfo/M2/Ml/MLD/projet/mlflow_run/231975655115258684/d6a0ed34f7344752ac260759357ab98b/artifacts/model
status: READY
status_message: null
storage_location: file:///D:/Supinfo/M2/Ml/MLD/projet/mlflow_run/231975655115258684/d6a0ed34f7344752ac260759357ab98b/artifacts/model
user_id: null
version: 1
