artifact_location: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/projet_mlops/scripts/mlflow_run/145848383788790988
creation_time: 1730995324178
experiment_id: '145848383788790988'
last_update_time: 1730995324178
lifecycle_stage: active
name: experience_1
