digest: f29fc928
name: dataset
profile: '{"num_rows": 61, "num_elements": 854}'
schema: '{"mlflow_colspec": [{"type": "long", "name": "age", "required": true}, {"type":
  "long", "name": "sex", "required": true}, {"type": "long", "name": "cp", "required":
  true}, {"type": "long", "name": "trestbps", "required": true}, {"type": "long",
  "name": "chol", "required": true}, {"type": "long", "name": "fbs", "required": true},
  {"type": "long", "name": "restecg", "required": true}, {"type": "long", "name":
  "thalach", "required": true}, {"type": "long", "name": "exang", "required": true},
  {"type": "double", "name": "oldpeak", "required": true}, {"type": "long", "name":
  "slope", "required": true}, {"type": "long", "name": "ca", "required": true}, {"type":
  "long", "name": "thal", "required": true}, {"type": "long", "name": "target", "required":
  true}]}'
source: '{"tags": {"mlflow.user": "alika", "mlflow.source.name": "scripts/pipeline_3.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "7fba9b3418e8f6a25cf75454eb87f5c593fd4680"}}'
source_type: code
