aliases: []
creation_timestamp: 1730997461797
current_stage: None
description: null
last_updated_timestamp: 1730997461797
name: RandomForest_Heart_Model
run_id: 863990024d6b48ea90ec915cd7deb4c6
run_link: null
source: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/863990024d6b48ea90ec915cd7deb4c6/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/863990024d6b48ea90ec915cd7deb4c6/artifacts/model
user_id: null
version: 4
