artifact_uri: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/bb7ce6748fb54861b6e9f7e59af0fff6/artifacts
end_time: 1730997559951
entry_point_name: ''
experiment_id: '664836091588214650'
lifecycle_stage: active
run_id: bb7ce6748fb54861b6e9f7e59af0fff6
run_name: sassy-fawn-699
run_uuid: bb7ce6748fb54861b6e9f7e59af0fff6
source_name: ''
source_type: 4
source_version: ''
start_time: 1730997552024
status: 3
tags: []
user_id: HP
