artifact_uri: file:///C:/Users/HP/Desktop/Scraping_GitHub_Topics-main/MLOPS/ops/projet_mlops/scripts/mlflow_run/664836091588214650/e531bba8b7124f6f90cdf35849785edf/artifacts
end_time: 1731009188179
entry_point_name: ''
experiment_id: '664836091588214650'
lifecycle_stage: active
run_id: e531bba8b7124f6f90cdf35849785edf
run_name: persistent-snail-737
run_uuid: e531bba8b7124f6f90cdf35849785edf
source_name: ''
source_type: 4
source_version: ''
start_time: 1731009188156
status: 4
tags: []
user_id: kanfa
